### ISSUE TITLE
Destroying session

### ISSUE THREAD

**Issue by colthreepv** [iamolegga/nestjs-cookie-session#124]
It does not seem possible with this library, how to achieve it?

**Comment by iamolegga** [comment]
https://www.npmjs.com/package/cookie-session#destroying-a-session

**Comment by colthreepv** [comment]
Hello, I know how to RTFM, the point was not to read the mainstream documentation when using this library.

For anyone interested, this is a simple copy-pasta to achieve it:
```typescript
@Controller()
export class ViewController {
  // .... other methods
  @Get('logout')
  @Render('logout')
  logoutGet (@Req() req: Request) {
    req.session = null
  }
}
```

**Comment by iamolegga** [comment]
Hi, feel free to open PR for adding this to documentation 👍
