### ISSUE TITLE
[QUESTION] Where can I import `Config` from?

### ISSUE THREAD

**Issue by alexhayes** [iamolegga/nestjs-cookie-session#712]
- [x] I've read [the docs](https://github.com/iamolegga/nestjs-cookie-session/blob/master/README.md)
- [x] I've read [the docs of cookie-session](https://www.npmjs.com/package/cookie-session)
- [x] I couldn't find the same [question](https://github.com/iamolegga/nestjs-cookie-session/issues?q=is%3Aissue+label%3Aquestion)

**Question**

This is perhaps a silly question, but in the docs it [injects something called `Config`](https://github.com/iamolegga/nestjs-cookie-session/blame/master/README.md#L57) but I can't work out where this exists. 

Is this part of NestJS? Is it something I'm supposed to create?

**Please mention other relevant information such as Node.js version and Operating System.**
- @nestjs/common ^9.0.0
- @nestjs/config ^2.2.0
- @nestjs/core ^9.0.0
- NodeJS v18.10.0
- OS: macOS Monterey 12.6

**Comment by alexhayes** [comment]
I think perhaps based upon [this](https://stackoverflow.com/a/52578302/3216868) maybe this has changed recently?

**Comment by iamolegga** [comment]
It could be any service that holds your settings, for example you can read [nestjs docs](https://docs.nestjs.com/techniques/configuration). The question is not relevant to the library, closing

**Comment by alexhayes** [comment]
HI @iamolegga - thank you for your response.

Note I had previously read the NestJS config docs, they make no mention of anything called `Config`, they do mention `ConfigService` many times, thus as a newcomer to NestJS it would be easier to use your library if the docs used the same naming as NestJS docs. I'm happy to submit a PR if you are open to accepting it?
